### ISSUE TITLE
Assalomu alaykum! itemlaga margin-right beribsiz ohirgi elementiga ham olib ketibti shuni :not(:last-child){margin-right:48px} va  headerni itemiga ham shuni  bersez yaxshi bo'lardi

### ISSUE THREAD

**Issue by shirinsultonova** [MuhammadAkbar-Ramazonov/Bookmark#1]
<img width="1309" alt="Снимок экрана 2022-07-25 в 17 21 21" src="https://user-images.githubusercontent.com/104461539/180776449-faa2ad0a-0baa-4997-a8c5-b5a684841bb4.png">

**Comment by MuhammadAkbar-Ramazonov** [comment]
valekum assalom,  assalomu aleykum xop raxmat to'g'irladim
